[package]
name = "nlp_decoder"
version = "0.1.0"
authors = ["darksrc"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#soup = "0.5.0"
webpage = "1.0.0"
#scraper = "0.11.0"
epub = "1.2.2"
regex = "1.3.4"
